server:
  port: 13001
spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    registerWithEureka: true  # 服务注册开关
    fetchRegistry: true        # 服务发现开关
    serviceUrl:                 # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://eureka20001.com:20001/eureka,http://eureka20002.com:20002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}   # 指定实例ID,就不会显 示主机名了
    prefer-ip-address: true   #访问路径可以显示IP地址

zuul:
  routes:
    povider-product:      # 路由名称，名称任意，保持所有路由名称唯一
      path: /product/**  # 访问路径
      serviceId: microservice-product # 指定服务ID，会自动从Eureka中找到此服务的ip和端
      stripPrefix: false  # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时 请求 /product/get/1，代理转发到/get/1