server:
  port: 11002
eureka:
  client:
    registerWithEureka: false  # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true    # 服务发现，从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka20001.com:20001/eureka,http://eureka20002.com:20002/eureka
# Feign是自带断路器的，也就是针对消费者（客户端）进行服务熔断,需要开启hystrix
feign:
  hystrix:
    enabled: true

# 在被监控服务上添加暴露端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream